name: iPhone Test
on: push

jobs:
  my-jobs:
    name: My Job
    runs-on: macOS-latest
    steps:
      - name: say hi
        env:
          NAME: iPhone 16
        run: |
          echo hey, $NAME > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt

      - name: 'use files'
        run: |
          echo use file `cat output.txt`

      - name: 'network'
        run: |
          curl https://apple.com

      - name: 'get ip'
        run: |
          curl https://ipinfo.io/ip
