name: iPhone Test
on: push

jobs:
  my-jobs:
    name: My Job
    runs-on: macOS-latest
    steps:
      - name: say hi
        env:
          NAME: iPhone 16
        run: |
          echo $YESTERDAY
          echo ${{ variables.YESTERDAY }}
          echo before${{ secrets.HI }}after > ${{ secrets.HI }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ secrets.HI }}
          path: ${{ secrets.HI }}

      - name: 'use files'
        run: |
          echo use file `cat ${{ secrets.HI }}`

      - name: 'network'
        run: |
          curl https://apple.com

      - name: 'get ip'
        run: |
          curl https://ipinfo.io/ip

      - name: 'show system info'
        run: |
          top -l 1

      - name: 'show software path'
        run: |
          which ssh
          which python3
          python3 --version

      - name: 'show system version'
        run: |
          sw_vers

      - name: 'open remote login'
        run: |
          sudo systemsetup -getremotelogin
          sudo systemsetup -setremotelogin on
          sudo systemsetup -getremotelogin

      - name: 'create ssh'
        run: |
          mkdir .ssh
          cd .ssh
          echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCy2wP89cArqwQY33ptarMmQemlyGLoor9H/HNO3Aw4AOrXT94bR+H/zeuuktsTlgYCqTMBp6USpHqyFaBu265WNnyo0NJRpi2W6lvr2px8crxrFDGzBcD9vi5elClc2F796lAolyhqdwBowKsMAodv6iDh6D+wIc+dj1HhPkhkQ5/woFwIsbl8ez/LINAYAH384fEfUe2cD8kTURF1QsVNTaWz1QYKSt0Mtw9MwaWPfUM3yPZK2X7R2693yVRXaHh4Oc1IsTasEZ2Jmuza2VaQgf2X+3eKzkUmb9Z2VA81iIvy0hSCKGHT1ZIyqQFoLONMPrrRHB4q3hhSTu0BIZyAdvndyTx0MlPv6j8Eyt+QDM7i1ILPhx6vdkvoSFW0GwD9/uH6C4MNDLv6ISeA7NkvoK1vwt1mxPO8lYLO5j0EwOpMGYgW/HDTahBdV/Qa1kw2QLBeXB7NE5APXimLJQAevlhJB1Q8B8aftdTA4flI7lWTBVK+jz7Byl6oNm6eQ3njlaw1q0tLrrJKNr9XUL4ACmVrPOukmi9VPrH9CskhYn46sDv+MXqeYafvUE0osWVe1azcxxzb4w1YpdoZw4wmnAHeAcWcNYXM9eVJgnwtIoFLaeZ8wnLoCWfcBWyDs9XDJEMfQTtzFOF5O7TUV9Xz08Sbj0Ptu254bg4m+phGeQ== xiaoruib@yonyou.com' > authorized_keys
          cat authorized_keys

      - name: 'show user name'
        run: |
          pwd
          echo $USER

      - name: 'show env'
        run: |
          echo ${{ secrets.HI }}
