name: iPhone Test
on: push

jobs:
  my-jobs:
    name: My Job
    runs-on: macOS-latest
    steps:
      - name: say hi
        env:
          NAME: iPhone 16
        run: |
          echo hey, $NAME > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: output.txt

      - name: 'use files'
        run: |
          echo use file `cat output.txt`

      - name: 'network'
        run: |
          curl https://apple.com

      - name: 'get ip'
        run: |
          curl https://ipinfo.io/ip

      - name: 'show system info'
        run: |
          top -l 1

      - name: 'show software path'
        run: |
          which ssh
          which python3
          python3 --version

      - name: 'show system version'
        run: |
          sw_vers

      - name 'open remote login':
        run: |
          sudo systemsetup -getremotelogin
          sudo systemsetup -setremotelogin on
          sudo systemsetup -getremotelogin
